### ISSUE TITLE
建议帖子

### ISSUE THREAD

**Issue by tonynesss** [LittleTurtle2333/Simplicity_Tools_Xposed#2]
1、居中挖孔，状态栏添加时钟显秒后左半部分状态栏基本没有空间显示通知图标了，能否添加一个网速右移+去除通知图标限制的功能，或者通过移除网速/s的图标来节省一些空间。
2、隐藏hd仅隐藏使用流量时的hd大方块，不隐藏使用wifi时信号上方的小hd图标，节省状态栏空间的同时也方便观察hd状态
3、使用定位时状态栏会有一个定位通知和一个定位图标显示，两者重复了，是否能加一个隐藏定位图标的功能？![Screenshot_2022-02-17-10-42-21-515_com.android.deskclock.png](https://user-images.githubusercontent.com/32998682/154395036-061a16c7-3fe2-4add-9166-2d467ca718fe.png)![Screenshot_2022-02-17-10-46-34-005_com.autonavi.minimap.png](https://user-images.githubusercontent.com/32998682/154395040-6608111d-820e-431d-afe6-3b0ff04236e6.png)

**Comment by winsmker** [comment]
![Screenshot_2022-02-17-10-51-09-944_com lt2333 simplicitytools](https://user-images.githubusercontent.com/55729100/154395807-a4f272d3-f24d-4ee2-b653-b40865d2ca03.jpg)
能不能只在没连接蓝牙设备的时候隐藏蓝牙图标，有耳机连接的时候正常显示蓝牙图标和设备电量图标

**Comment by tonynesss** [comment]
> ![Screenshot_2022-02-17-10-51-09-944_com lt2333 simplicitytools](https://user-images.githubusercontent.com/55729100/154395807-a4f272d3-f24d-4ee2-b653-b40865d2ca03.jpg)
> 能不能只在没连接蓝牙设备的时候隐藏蓝牙图标，有耳机连接的时候正常显示蓝牙图标和设备电量图标

用自动任务可以实现断开蓝牙后自动关闭蓝牙

**Comment by LittleTurtle2333** [comment]
v1.0.8已支持
