### ISSUE TITLE
隐藏HD问题

### ISSUE THREAD

**Issue by wuliyu007** [LittleTurtle2333/Simplicity_Tools_Xposed#3]
隐藏后状态栏会显示volte未打开  实际功能正常
![Screenshot_2022-02-17-15-46-11-922_com lt2333 simplicitytools](https://user-images.githubusercontent.com/56251067/154429395-53fc7de9-09d4-4427-bdf8-49177dee7e73.jpg)
![Screenshot_2022-02-17-15-46-38-702_com lt2333 simplicitytools](https://user-images.githubusercontent.com/56251067/154429405-ad9680f8-c17e-44ac-9688-0c28189611fb.jpg)

版本1.0.4   双电信卡

**Comment by LittleTurtle2333** [comment]
v1.0.5 已修复
