### ISSUE TITLE
深色模式下界面显示问题

### ISSUE THREAD

**Issue by MidNightBlackCat** [LittleTurtle2333/Simplicity_Tools_Xposed#9]
深色模式下
1. 右上角菜单看不见
2. 状态栏颜色与界面不一致，不支持沉浸
![Screenshot_2022-02-18-23-02-24-629_com lt2333 simplicitytools](https://user-images.githubusercontent.com/14031735/154707761-a9997b56-aa34-4727-8279-41649bff7a2f.jpg)

**Comment by LittleTurtle2333** [comment]
1.1.2已修复

**Comment by MidNightBlackCat** [comment]
> 

666，大佬高产
